### ISSUE TITLE
Editing main.py for accepting extra command-line options

### ISSUE THREAD

**Issue by AndroXD** [mathigatti/RealTimeSingingSynthesizer#1]
Hello,
Sorry for being a total python noob, to my understanding, main.py creates 3 files on /tmp ("last_midi_generated_by_vrender.mid", "last_voice.musicxml" and "last_voice.xml") with my lyrics on repeat to the 4 notes that are hardcoded, then outputs a "output.wav" file, however, when trying to define a tempo and custom output name (as mentioned in the README.md file) doesn't seem to have any effect at all.
Can you show me how to have a fully working main.py please ? The idea is to use a command-line such as "python main.py singing_output.wav "some lyrics to sing" 100 song.mid".
Until now I managed to do it manually with "musescore ./tmp/song.mid -o ./tmp/last_voice.musicxml", run main.py but preventing musescore to be found so it won't not generate a "last_midi_generated_by_vrender.mid" on ./tmp but will generate a valid "last_voice.xml" from the "last_voice.musicxml" I created before, then load "sinsyNG -m en -o output.wav ./tmp/last_voice.xml", however, the output duration is much longer than the actual midi (ie. output.wav is 6 minutes vs song.mid is 3 minutes), I couldn't figure out how to manually change the tempo so the output.wav lyrics matches with the midi instruments.
Any help is much appreciated, thank you for your kind attention!

**Comment by mathigatti** [comment]
Hi! Sorry about that, there was a bug in the code, I was ignoring tempo and the output file name. I updated it, please check it and let me know if everything is okay now.

**Comment by AndroXD** [comment]
Woah! That was so fast! Thanks a billion, it works perfectly now!

**Comment by mathigatti** [comment]
Great :D You're welcome!
