### ISSUE TITLE
Resulting output never matches the MIDI file perfectly

### ISSUE THREAD

**Issue by AndroXD** [mathigatti/RealTimeSingingSynthesizer#2]
Hello,
Is there any "magic trick/formula" to guarantee that the lyrics will always match the midi file when you play them together? My resulting output sounds good to the ear and nothing seems out of place until I add the midi instrumentals in the background, the timing is off even if the output was generated using the same tempo or the two files have the same duration, even when after some tweaking the lyrics are pronounced with the correct timing, the duration of the entire file is off, so I have to manually cut and paste the lyrics from an audio editor and glue them in the correct place, which is quite a tedious work. It would be great if it was possible to play the resulting output and midi file together right out of the box, or understand the logic why this problem happens.
Thanks for the amazing repo, I'm really enjoying this.

**Comment by mathigatti** [comment]
You're welcome :)

I use this for realtime synthesis and it seems to obey the specified BPMs and durations but I haven't tried to couple it with a MIDI file. Maybe the vocals and instruments are a little bit dephased? Send me the files you are using (through google drive or whatever) and I will check if it's something easy to automatize.

In [this](https://github.com/mathigatti/midi2voice) other repo I use the sinsy.jp synthesizer and a midi file as input, there I show a simple example of the song "Somebody That I Used To Know", the lyrics are not well synched but the notes and duration of each note are fine. I just joined the vocals and instruments into one single audio file without much troubles.

**Comment by AndroXD** [comment]
I managed to solve the problem, when I tried your MIDI file it worked right out of the box, so I investigated why mine didn't, I discovered that sometimes MIDI files generated from neural networks have just the bare minimum information to make them playable, they just don't have a lot of information that is usually contained in MIDI files by default, I'll call this portion of information a "ghost track", it's kind like EXIF data in pictures, turns out this "ghost track" was completely empty or missing, the consequence was that the MIDI editor would use its default BPM value and it would sound good, but when saving the file, it would silently and without giving any errors or warnings not including or put a wrong BPM in the saved file, even if you did specify a custom one in the editor, it would either not use it or put a wrong one. Here's an example of a good and bad midi file: https://i.imgur.com/RB9DUEs.gif
To fix it, I used Sekaiju downloadable here: https://openmidiproject.osdn.jp/index_en.html and did this: https://i.imgur.com/hR36cZh.gif
Hope it can be helpful if someone else is facing the same problem.

**Comment by mathigatti** [comment]
Excellent, thanks for details.

**Comment by mathigatti** [comment]
Are you generating MIDIs with neural networks and using this project to add vocals to the final song? If that's the case that's really cool.
